---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: _data/laboratorio.yml
  label: Laboratório
- type: heading
  label: FUSO INSULAR
- type: document
  path: _data/open-call.yml
  label: Open Call
- type: document
  path: _data/sobre-fuso.yml
  label: Sobre
- type: heading
  label: FUSO
- type: document
  path: _data/sobre-insular.yml
  label: Sobre
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
